FROM archlinux
RUN echo "Yes" | pacman --noconfirm -Syy && wcho "Yes" | pacman --noconfirm -Syu
RUN echo "Yes" | pacman --noconfirm -S git base-devel lsb-release
RUN mkdir -p /mps/mps-docker
RUN git clone https://github.com/livemps/mps-docker /mps/mps-docker
RUN chmod a+rw -R /mps
RUN cd /mps && git pull && make DISTRO=arch install
USER mps
WORKDIR /home/mps
ENTRYPOINT ["/bin/bash"]
