FROM debian
RUN apt update --yes && apt upgrade --yes
RUN apt install --yes git build-essential
RUN mkdir -p /mps
RUN git clone https://github.com/livemps/mps-docker /mps/mps-docker
RUN cd /mps/mps-docker && git pull && make install
RUN chmod a+rw -R /mps
USER mps
WORKDIR /home/mps
ENTRYPOINT ["/bin/bash"]
