FROM archlinux
RUN echo "Yes" | pacman --noconfirm -Syy && wcho "Yes" | pacman --noconfirm -Syu
RUN echo "Yes" | pacman --noconfirm -S git base-devel
RUN git clone https://github.com/livemps/mps-docker /mps
RUN chmod a+rw -R /mps
RUN cd /mps && git pull && make install
USER mps
WORKDIR /home/mps
ENTRYPOINT ["/bin/bash"]
